name: ifdconnect
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
 # google_sign_in: 4.5.1
  firebase_storage: 3.1.6
  connectivity:
  image_picker:
  timeago:
    path: plugins/timeago-2.0.1/
  latlong:
  flutter_linkify: 3.0.0
  image_cropper: 1.1.1
  geolocator: #7.3.0
  shared_preferences:
  photo_view:
  #flutter_spinkit: 4.1.2+1
  #flutter_swiper:
  #  path: plugins/flutter_swiper-master 4
  shimmer:
  flutter_search_bar:
  animated_text_kit: ^1.1.1
  share: 0.6.4+3
  url_launcher:
  cached_network_image: 2.0.0
  location:
    path: location-3.1.0
  #flutter_widget_from_html:
  uuid:
  audioplayer: 0.8.1
  random_string: ^0.0.2
  bubble_tab_indicator: 0.1.4
  flutter_svg: 0.19.3
  rflutter_alert: 1.0.3
  mime:
  percent_indicator: 2.1.5
  mime_type:
  flutter_document_picker: 4.0.1
  scoped_model:
  #firebase_dynamic_links: ^0.5.0
  #json_annotation:
 # image:
  parse_server_sdk: 1.0.28
  random_color: ^1.0.5
  #flutter_facebook_login: 3.0.0
  firebase_analytics: 5.0.15
  firebase_auth: 0.14.0+8

  flutter_native_image: 0.0.4
  firebase_messaging: 5.1.8
  firebase_database: 3.0.9
  flutter_swiper:
  flutter_webview_plugin: 0.3.10
  webview_flutter:   0.3.24
  cloud_firestore: 0.12.10
  flutter_sound: ^2.0.1
  #audioplayers:
  bubble_bottom_bar:
  #flutter_youtube:
  sticky_headers:
  flutter_slidable: 0.6.0
  http: 0.12.1
  #card_settings:  1.4.0
  datetime_picker_formfield: 0.2.0
  flutter_widget_from_html: 0.3.2
  flutter_rounded_date_picker: 2.0.2
  syncfusion_flutter_datepicker: 20.1.48
  flutter_holo_date_picker: 1.0.3
  equatable:
  flutter_bloc: 7.0.0
  dropdown_search: ^2.0.1
  flutter_screenutil: 5.0.0+2
  splashscreen: 1.3.5
  carousel_slider: 4.0.0
  youtube_plyr_iframe: 2.0.7
  carousel_pro: 1.0.0
  google_fonts: 1.1.2
  chat_bubbles: ^1.2.0
  flutter_chat_bubble: ^2.0.0

  flutter_test:
    sdk: flutter

  flutter_launcher_icons:
  firebase_remote_config: ^0.3.1+1

flutter_icons:
  image_path: "images/launcher_icon_ifd.png"
  android: true
  ios: false

dependency_overrides:
  intl: ^0.17.0
  chewie:
    path: plugins/chewie-0.10.4/ # intl: 0.16.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - assets/icons/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helveticaneue.ttf
    - family: Hbold
      fonts:
        - asset: assets/fonts/Helvetica-Neue-Bold_22498.ttf
    - family: Helvetica_neu
      fonts:
        - asset: assets/fonts/Helvetica Neue Medium Extended.otf